// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}},
{"name":"OcRam_Audio_EX","status":false,"description":"v2.12 This plugin provides dynamic sound positioning and adds 2 'generic' BGS channels which will also play in battle. PLUGIN NAME MUST BE OcRam_Audio_EX.js","parameters":{"Default Distance (BGS/SE)":"20","Default Radius (BGS/SE)":"0","Default create new (BGS)":"false","Default fade (BGS)":"2","Default forced play (BGS)":"true","Default autopan (BGS/SE)":"true","Default fade (BGM)":"2","BGS2/3 volume control":"true","BGS2 option caption":"BGS2 Volume","BGS3 option caption":"BGS3 Volume","Use linear curve":"true","Debug mode":"false"}},
{"name":"MOG_TitleCommands","status":true,"description":"(v1.3) Adiciona comandos em imagens no lugar da janela.","parameters":{"-> Main <<<<<<<<<<<<<<<<<<<<<<<":"","Animation Mode":"0","Left & Right Input":"true","Shake Duration":"50","Slide X-Axis":"-100","Slide Y-Axis":"0","-> Cursor <<<<<<<<<<<<<<<<<<<<<<<":"","Cursor X-Axis":"0","Cursor Y-Axis":"5","Cursor Visible":"false","Cursor Wave Animation":"true","Cursor Rotation Animation":"false","Cursor Rotation Speed":"0.05","-> Commands <<<<<<<<<<<<<<<<<<<<<<<":"","Command Pos 1":"180,400","Command Pos 2":"350,400","Command Pos 3":"520,400","Command Pos 4":"690,440","Command Pos 5":"345,498","Command Pos 6":"345,530","Command Pos 7":"0,192","Command Pos 8":"0,224","Command Pos 9":"0,256","Command Pos 10":"0,288"}}
];
